#!/usr/bin/env bash
# .claude/hooks/post-write.sh
# Fires after every Write/Edit/MultiEdit on TypeScript/TSX files.
#
# Two severities:
#   BLOCKERS (exit 2) — the agent MUST fix before continuing. These are correctness
#     /security violations that should never land: editing the read-only generated
#     contract, or putting an auth token in web storage.
#   WARNINGS (exit 0) — printed for the agent to address before commit, but not fatal.
#
# Exit-code contract (Claude Code PostToolUse): a non-zero exit (2) with text on stderr
# is fed back to the agent as a required fix. Exit 0 with text on stdout is advisory.
#
# Parses the PostToolUse hook JSON from stdin with `node` (always present in a Node
# project) — no python3 dependency. Normalises the absolute path Claude Code sends
# (incl. Windows backslashes) to a repo-relative, forward-slash path so the layer
# checks below actually match.

set -euo pipefail

RAW=$(cat)

# Extract the written file path. Claude Code puts it at tool_input.file_path;
# fall back to other shapes defensively.
FILE=$(printf '%s' "$RAW" | node -e "
let d='';
process.stdin.on('data', c => d += c).on('end', () => {
  try {
    const j = JSON.parse(d);
    const p = (j.tool_input && j.tool_input.file_path)
      || (j.tool_response && j.tool_response.filePath)
      || j.file_path || j.path || '';
    process.stdout.write(p || '');
  } catch { process.stdout.write(''); }
});
" 2>/dev/null || echo "")

[[ -z "$FILE" ]] && exit 0

# Normalise backslashes → forward slashes for portable matching.
NORM="${FILE//\\//}"

# ── BLOCKER: tests/acceptance/ is a HOLDOUT — writable ONLY during the spec phase ──
# /write-spec drops .rigel/acceptance.unlock while it scaffolds the failing acceptance
# tests, then removes it. A write here without that marker is a build-phase edit to the
# holdout set (test tampering) and must be reverted. Fail-closed: no marker → blocked.
# Placed BEFORE the -f / extension filters so ANY file under tests/acceptance/ (a brand
# new file, a .tsx test, or a non-source fixture) is caught, not just existing .ts files.
if [[ "$NORM" =~ (^|/)tests/acceptance/ ]]; then
  MARKER="${CLAUDE_PROJECT_DIR:-.}/.rigel/acceptance.unlock"
  if [[ ! -f "$MARKER" ]]; then
    echo "🚫 [HOOK] $NORM is a HOLDOUT acceptance test — editable only during the spec phase (/write-spec). Revert this change. Acceptance tests encode the spec's success criteria and must not be altered while building." >&2
    exit 2
  fi
fi

[[ ! -f "$FILE" ]] && exit 0
# Rigel's TS-specific checks below run for .ts/.tsx; design-bearing files (.tsx/.jsx/.css/
# .mdx) additionally get the Impeccable tier at the end. Anything else is ignored.
[[ ! "$FILE" =~ \.(ts|tsx|jsx|css|mdx)$ ]] && exit 0

WARNINGS=()
BLOCKERS=()

# ── BLOCKER 1: api.generated.ts is READ ONLY ───────────────────────────────
# Editing the generated contract by hand breaks the single source of truth.
if [[ "$NORM" =~ api\.generated\.ts$ ]]; then
  BLOCKERS+=("🚫 [HOOK] $NORM is READ ONLY — it is regenerated by /api-sync. Revert this edit and run /api-sync against openapi.json instead.")
fi

# ── BLOCKER 2: auth tokens must never touch web storage ────────────────────
# Broadened from the old "token must be literally inside setItem(...)" grep so
# `localStorage.setItem('auth', accessToken)` (key does not contain "token") is
# caught too. Matches any setItem whose call references an auth-ish identifier.
if grep -qniE "(local|session)Storage\.setItem\([^)]*(token|jwt|auth|bearer|access|refresh|secret|credential)" "$FILE" 2>/dev/null; then
  LINE=$(grep -niE "(local|session)Storage\.setItem" "$FILE" | head -1 | cut -d: -f1)
  BLOCKERS+=("🚫 [HOOK] Token/credential written to web storage at $NORM:$LINE — access tokens must stay in memory (React context). Revert.")
fi

# ── WARNING 1: console.log in src/ or app/ (no structured console logging) ──
# Use the structured logger (src/lib/logger.ts) instead; raw console.log is noise.
if [[ "$NORM" =~ (^|/)src/ ]] || [[ "$NORM" =~ (^|/)app/ ]]; then
  if grep -qn "console\.log\b" "$FILE" 2>/dev/null; then
    LINE=$(grep -n "console\.log\b" "$FILE" | head -1 | cut -d: -f1)
    WARNINGS+=("⚠ [HOOK] console.log at $NORM:$LINE — use the structured logger from src/lib/logger.ts (or remove before committing)")
  fi
fi

# ── WARNING 2: process.env outside src/lib/ (env.ts validates NEXT_PUBLIC_*) ──
# NODE_ENV / NEXT_RUNTIME are build-time constants Next inlines — not flagged.
# src/lib/ is the infra boundary (env.ts, logger.ts) and may read them.
if [[ "$NORM" =~ (^|/)src/ ]] && [[ ! "$NORM" =~ (^|/)src/lib/ ]]; then
  if grep -nE "process\.env" "$FILE" 2>/dev/null | grep -vqE "process\.env\.(NODE_ENV|NEXT_RUNTIME)\b"; then
    LINE=$(grep -nE "process\.env" "$FILE" | grep -vE "process\.env\.(NODE_ENV|NEXT_RUNTIME)\b" | head -1 | cut -d: -f1)
    WARNINGS+=("⚠ [HOOK] process.env at $NORM:$LINE — use env from src/lib/env.ts")
  fi
fi

# ── WARNING 3: direct fetch() in components, features, or pages ─────────────
# Anchored so it does NOT false-positive on TanStack's refetch()/prefetchQuery()
# (fetch preceded by a letter or a dot is someone else's method, not a bare fetch).
if [[ "$NORM" =~ (^|/)(src/features|src/components|app)/ ]]; then
  if grep -qnE "(^|[^A-Za-z.])fetch\(" "$FILE" 2>/dev/null; then
    LINE=$(grep -nE "(^|[^A-Za-z.])fetch\(" "$FILE" | head -1 | cut -d: -f1)
    WARNINGS+=("⚠ [HOOK] Direct fetch() at $NORM:$LINE — API calls must go through src/hooks/")
  fi
fi

# ── WARNING 4: raw <img> tag (should use next/image) ───────────────────────
if [[ "$NORM" =~ \.tsx$ ]]; then
  if grep -qn "<img " "$FILE" 2>/dev/null; then
    LINE=$(grep -n "<img " "$FILE" | head -1 | cut -d: -f1)
    WARNINGS+=("⚠ [HOOK] <img> at $NORM:$LINE — use next/image <Image /> component")
  fi
fi

# ── WARNING 5: file size > 400 lines ───────────────────────────────────────
LINE_COUNT=$(wc -l < "$FILE" 2>/dev/null || echo 0)
if [[ "$LINE_COUNT" -gt 400 ]]; then
  WARNINGS+=("⚠ [HOOK] $NORM has $LINE_COUNT lines — exceeds 400-line limit. Split into focused modules.")
fi

# Print advisory warnings to stdout (guard empty array for bash 3.2 / set -u).
if [[ ${#WARNINGS[@]} -gt 0 ]]; then
  for w in "${WARNINGS[@]}"; do
    echo "$w"
  done
fi

# Blockers go to stderr and fail the hook so the agent must address them.
# Rigel's own blockers run FIRST — architecture/security beat aesthetics.
if [[ ${#BLOCKERS[@]} -gt 0 ]]; then
  for b in "${BLOCKERS[@]}"; do
    echo "$b" >&2
  done
  exit 2
fi

# ── Impeccable design-quality tier (PLAN-005 AC-3) ─────────────────────────────
# Runs only after Rigel's blockers passed. Slop antipatterns block (exit 2); craft
# findings are advisory. Design-bearing files only. `exec` hands the tier's exit code
# straight back as the hook's. Skips cleanly (falls through to exit 0) if the tier or
# Impeccable isn't present (e.g. a bare scaffold before /infra-setup).
if [[ "$FILE" =~ \.(tsx|jsx|css|mdx)$ ]]; then
  TIER="${CLAUDE_PROJECT_DIR:-.}/.claude/hooks/impeccable-tier.mjs"
  [[ -f "$TIER" ]] && exec node "$TIER" "$FILE"
fi

exit 0
